version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "daily"

  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "4.x"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "4.x"
    schedule:
      interval: "daily"
