language: java
jdk:
  - openjdk7
  - oraclejdk8
  - oraclejdk9

# No need for preliminary install step.
install: true
#
# Run all integration tests.
script: 
  - "mvn --show-version --errors --batch-mode clean verify"
#
cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
notifications:
    email:
        - khmarbaise@apache.org
