# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
#    name: JDK ${{ matrix.jdk }} on ${{ matrix.os }}
#
#    runs-on: ${{ matrix.os }}
#    
#    strategy:
#      matrix:
#        os: [ubuntu-latest, macos-latest, windows-latest]
#        jdk: [7, 8, 11]

#    steps:
#    - uses: actions/checkout@v2
#    - name: Set up JDK
#      uses: actions/setup-java@v1
#      with:
#        java-version: ${{ matrix.jdk }}
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Dependencies Cache
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: mvn-${{ hashFiles('pom.xml') }}
    - name: Build
      run: mvn -B package --file pom.xml
